PRINT = False

ONE_ATOM_NODE_CN = (True, {'Zn':4,'C':4})

CONNECTION_SITE_BOND_LENGTH = 1.7
YOU_ARE_PATIENT = False

CHECK_NUMBER_OF_VERTICES_AND_EDGES = False
WRITE_CHECK_FILES = False
WRITE_CIF = True

USER_SPECIFIED_NODE_ASSIGNMENT = False
COMBINATORIAL_EDGE_ASSIGNMENT = False
CHARGES = False

SYMMETRY_TOL = {2:0.1, 3:0.2, 4:0.2, 5:0.2, 6:0.2, 7:0.5, 8:0.5, 9:0.5, 10:0.5, 12:0.5, 24:1.0}
BOND_TOL = 10.0
EXPANSIVE_BOND_SEARCH = False
TRACE_BOND_MAKING = False
NODE_TO_NODE = True
SINGLE_ATOM_NODE = True
ORIENTATION_DEPENDENT_NODES = True

PLACE_EDGES_BETWEEN_CONNECTION_POINTS = True